JobStack/src/WebUI/Areas/Manage/Controllers/CandidateController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using WebUI.Models;

namespace JobStack.WebUI.Areas.Manage.Controllers;

[Area("Manage")]
public class CandidateController : Controller
{
    Uri baseUrl = new("http://localhost:7264/api");
    private readonly HttpClient _client;

    public CandidateController(HttpClient client)
    {
        _client = client;
        _client.BaseAddress = baseUrl;
    }
    public IActionResult Index()
    {
        List<CandidateVM> candidates = new();
        HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Candidates/ManageGetAllCandidates").Result;
        if (response.IsSuccessStatusCode)
        {
            string data = response.Content.ReadAsStringAsync().Result;
            candidates = JsonConvert.DeserializeObject<List<CandidateVM>>(data);
            return View(candidates);
        }
        return RedirectToAction("Index", "Errors");
    }
    public IActionResult Delete(int id)
    {
        string data = id.ToString();
        StringContent content = new(data, Encoding.UTF8, "application/json");
        HttpResponseMessage result = _client.PostAsync(_client.BaseAddress + $"/Candidates/Delete?id={id}", content).Result;
        if (result.IsSuccessStatusCode)
        {
            return RedirectToAction(nameof(Index));
        }
        return RedirectToAction("Index", "Errors");
    }
    public IActionResult PermaDelete(int id)
    {
        string data = id.ToString();
        StringContent content = new(data, Encoding.UTF8, "application/json");
        HttpResponseMessage result = _client.PostAsync(_client.BaseAddress + $"/Candidates/PermaDelete?id={id}", content).Result;
        if (result.IsSuccessStatusCode)
        {
            return RedirectToAction(nameof(Index));
        }
        return RedirectToAction("Index", "Errors");
    }
}

JobStack/src/WebUI/Controllers/CandidatesController.cs
using JobStack.WebUI.DTOs.Candidate;
using JobStack.WebUI.Utilities;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using WebUI.Models;


namespace JobStack.WebUI.Controllers;

public class CandidatesController : Controller
{
    Uri baseUrl = new("http://localhost:7264/api");
    private readonly HttpClient _client;
    private readonly IWebHostEnvironment _env;

    public CandidatesController(HttpClient client, IWebHostEnvironment env)
    {
        _client = client;
        _client.BaseAddress = baseUrl;
        _env = env;
    }

    public IActionResult Index()
    {
        List<CandidateVM> candidates = new();
        HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Candidates/GetAllCandidates").Result;
        if (response.IsSuccessStatusCode)
        {
            string data = response.Content.ReadAsStringAsync().Result;
            candidates = JsonConvert.DeserializeObject<List<CandidateVM>>(data);
            return View(candidates);
        }
        return RedirectToAction("Index", "Error");
    }
    public IActionResult Details(int id)
    {
        List<CandidateVM> candidates = new();
        HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + $"/Candidates/Details/{id}").Result;
        if (response.IsSuccessStatusCode)
        {
            string data = response.Content.ReadAsStringAsync().Result;
            candidates = JsonConvert.DeserializeObject<List<CandidateVM>>(data);
            ViewBag.Skills = JsonConvert.DeserializeObject<string[]>(candidates[0].CandidateSkillName);
            return View(candidates[0]);
        }
        return RedirectToAction("Index", "Error");
    }


    private List<CountryVM> CountryAll()
    {
        List<CountryVM> countries = new();
        HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Countries/GetAllCountries").Result;
        if (response.IsSuccessStatusCode)
        {
            string data = response.Content.ReadAsStringAsync().Result;
            countries = JsonConvert.DeserializeObject<List<CountryVM>>(data);
        }
        return countries;
    }
    private List<CityVM> CityAll()
    {
        List<CityVM> cities = new();
        HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Cities/GetAllCities").Result;
        if (response.IsSuccessStatusCode)
        {
            string data = response.Content.ReadAsStringAsync().Result;
            cities = JsonConvert.DeserializeObject<List<CityVM>>(data);
        }
        return cities;
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
        List<CandidateEditDto> candidates = new();
        HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + $"/Candidates/Details/{id}").Result;
        if (response.IsSuccessStatusCode)
        {
            string data = response.Content.ReadAsStringAsync().Result;
            candidates = JsonConvert.DeserializeObject<List<CandidateEditDto>>(data);
            TempData["OldImage"] = candidates[0].CandidateProfilImage;
            TempData["OldCV"] = candidates[0].CandidateCV;
            var test = JsonConvert.DeserializeObject<string[]>(candidates[0].CandidateSkillName);
            ViewBag.Countries = CountryAll();
            ViewBag.Cities = CityAll();
            ViewBag.Skills = JsonConvert.DeserializeObject<string[]>(candidates[0].CandidateSkillName);
            return View(candidates[0]);
        }
        return RedirectToAction("Index", "Error");
    }
    [HttpPost]
    public IActionResult Edit(string skills, CandidateEditDto candidateEdit)
    {
        var imagefolderPath = Path.Combine(_env.WebRootPath, "data", "candidate", "images");
        var cvfolderPath = Path.Combine(_env.WebRootPath, "data", "candidate", "resume");
        string imagereturnPath = candidateEdit.CandidateProfileUrl.SaveFile(imagefolderPath);
        string cvreturnPath = candidateEdit.CandidateCVUrl.SaveFile(cvfolderPath);
        CandidateUpdateDto candidateUpdate = new()
        {
            CandidateId = candidateEdit.Id,
            CandidateCV = cvreturnPath,
            CandidateEmail = candidateEdit.CandidateEmail,
            CandidateFirstName = candidateEdit.CandidateFirstName,
            CandidateLastName = candidateEdit.CandidateLastName,
            CandidateProfession = candidateEdit.CandidateProfession,
            CandidateProfilImage = imagereturnPath,
            CandidateSkillName = candidateEdit.CandidateSkillName,
            CityId = candidateEdit.CityId,
            CountryId = candidateEdit.CountryId,
            Description = candidateEdit.Description,
        };
        string data = JsonConvert.SerializeObject(candidateUpdate);
        StringContent content = new(data, Encoding.UTF8, "application/json");
        HttpResponseMessage result = _client.PutAsync(_client.BaseAddress + "/Candidates/Put", content).Result;
        HttpResponseMessage response = result;
        if (response.IsSuccessStatusCode)
        {
            string OldPicture = TempData["OldImage"] as string;
            string OldCV = TempData["OldCV"] as string;

            var fullImagePath = Path.Combine(imagefolderPath, OldPicture);
            var fullCvPath = Path.Combine(cvfolderPath, OldCV);
            if (System.IO.File.Exists(fullCvPath)) System.IO.File.Delete(fullCvPath);
            if (System.IO.File.Exists(fullImagePath)) System.IO.File.Delete(fullImagePath);
            return RedirectToAction(nameof(Index));
        }
        return RedirectToAction("Index", "Error");
    }
    public IActionResult Delete(int id)
    {
        string data = id.ToString();
        StringContent content = new(data, Encoding.UTF8, "application/json");
        HttpResponseMessage result = _client.PostAsync(_client.BaseAddress + $"/Candidates/Delete?id={id}", content).Result;
        if (result.IsSuccessStatusCode)
        {
            return RedirectToAction(nameof(Index));

        }
        return RedirectToAction("Index", "Error");
    }
}

JobStack/src/WebUI/Views/Candidates/Edit.cshtml
@model JobStack.WebUI.DTOs.Candidate.CandidateEditDto

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
}

<!-- Start Hero -->
<section class="relative lg:mt-24 mt-[74px] pb-16">
    <div class="lg:container container-fluid">
        <div class="profile-banner relative text-transparent">
            @*<input id="pro-banner" name="profile-banner" type="file" class="hidden" onchange="loadFile(event)">*@
            <div class="relative shrink-0">

                <img src="~/assets/images/hero/bg4.jpg" class="h-64 w-full object-cover lg:rounded-xl shadow dark:shadow-gray-700" id="profile-banner" alt="">
                
                <label class="absolute inset-0 cursor-pointer" ></label>
            </div>
        </div>
        <!-- <div class="relative shrink-0">
            <img src="assets/images/hero/bg5.jpg" class="h-64 w-full object-cover lg:rounded-xl shadow dark:shadow-gray-700" alt="">
        </div> -->

        <div class="md:flex mx-4 -mt-12">
            <div class="md:w-full">
                <div class="relative flex items-end">
                    <div class="profile-pic text-center">
                        @*<input id="pro-img" name="profile-image" type="file" class="hidden" onchange="loadFile(event)">*@
                        <div>
                            <div class="relative h-28 w-28 max-w-[112px] max-h-[112px] mx-auto">
                                @if(Model.CandidateProfilImage is not null)
                                {
                                   <img src="~/data/candidate/images/@Model.CandidateProfilImage" class="rounded-full shadow dark:shadow-gray-800 ring-4 ring-slate-50 dark:ring-slate-800" id="profile-image" alt="">

                                }
                               
                                <label class="absolute inset-0 cursor-pointer" for="pro-img"></label>
                            </div>
                        </div>
                    </div>
                    <div class="ms-4">
                        <h5 class="text-lg font-semibold">@Model.CandidateFirstName @Model.CandidateLastName</h5>
                        <p class="text-slate-400">@Model.CandidateProfession</p>
                    </div>
                </div>
            </div>
        </div>
    </div><!--end -->

    <div class="container mt-16">
        <div class="grid grid-cols-1 gap-[30px]">
            <div class="p-6 rounded-md shadow dark:shadow-gray-800 bg-white dark:bg-slate-900">
                <h5 class="text-lg font-semibold mb-4">Personal Detail :</h5>
                <form  asp-action="Edit" enctype="multipart/form-data">
                    <div class="grid lg:grid-cols-2 grid-cols-1 gap-4">
                        <div>
                            <label asp-for="CandidateFirstName" class="form-label font-medium">First Name : <span class="text-red-600">*</span></label>
                            <input asp-for="CandidateFirstName" class="form-input border border-slate-100 dark:border-slate-800 mt-2" placeholder="First Name:" id="firstnameId">
                            <span asp-validation-for="CandidateFirstName" class="text-red-600"></span>
                        </div>
                        <div>
                            <label asp-for="CandidateLastName" class="form-label font-medium">Last Name : <span class="text-red-600">*</span></label>
                            <input asp-for="CandidateLastName" class="form-input border border-slate-100 dark:border-slate-800 mt-2" placeholder="Last Name:" id="lastnameId">
                            <span asp-validation-for="CandidateLastName" class="text-red-600"></span>

                        </div>
                        <div>
                            <label asp-for="CandidateEmail" class="form-label font-medium">Your Email : <span class="text-red-600">*</span></label>
                            <input asp-for="CandidateEmail" class="form-input border border-slate-100 dark:border-slate-800 mt-2" placeholder="Email" id="emailId">
                            <span asp-validation-for="CandidateEmail" class="text-red-600"></span>

                        </div>
                        <div>
                            <label asp-for="CandidateProfession" class="form-label font-medium">Your Profession : <span class="text-red-600">*</span></label>
                            <input asp-for="CandidateProfession" class="form-input border border-slate-100 dark:border-slate-800 mt-2" placeholder="Web Developer" id="professionId">
                            <span asp-validation-for="CandidateProfession" class="text-red-600"></span>

                        </div>
                        <div>
                            <label asp-for="CountryId" class="form-label font-medium">Country :</label>
                            <select id="countryId" asp-for="CountryId" asp-items="@(new SelectList(ViewBag.Countries,nameof(CountryVM.Id),nameof(CountryVM.Name)))" class="form-select form-input border border-slate-100 dark:border-slate-800 block w-full mt-2">
                                @*<option value="WD">Web Designer</option>
                                <option value="WD">Web Developer</option>
                                <option value="UI">UI / UX Desinger</option>*@
                            </select>
                        </div>
                        <div>
                            <label asp-for="CityId" class="form-label font-medium">City :</label>
                            <select id="cityId" asp-for="CityId" asp-items="@(new SelectList(ViewBag.Cities,nameof(CityVM.Id),nameof(CityVM.CityName)))" class="form-select form-input border border-slate-100 dark:border-slate-800 block w-full mt-2">
                                @*<option value="NY">New York</option>
                                <option value="MC">North Carolina</option>
                                <option value="SC">South Carolina</option>*@
                            </select>
                        </div>
                        <div>
                             <a href="~/data/candidate/resume/@Model.CandidateCV" target="_blank" class="btn btn-sm bg-emerald-600 hover:bg-emerald-700 border-emerald-600 dark:border-emerald-600 text-white rounded-md">Open CV</a>
                            <label asp-for="CandidateCVUrl" class="form-label font-medium">Upload Resume:</label>
                            <input id="cvId" asp-for="CandidateCVUrl" class="relative form-input border border-slate-100 dark:border-slate-800 file:h-10 file:-mx-3 file:-my-2 file:cursor-pointer file:rounded-none file:border-0 file:px-3 file:text-neutral-700 bg-clip-padding px-3 py-1.5 file:me-3 mt-2">
                            <span asp-validation-for="CandidateCVUrl" class="text-red-600"></span>
                        </div> 
                        <div>
                            <label asp-for ="CandidateProfileUrl" class="form-label font-medium">Upload Profil Image:</label>
                            <input id="imageId" asp-for="CandidateProfileUrl" class="relative form-input border border-slate-100 dark:border-slate-800 file:h-10 file:-mx-3 file:-my-2 file:cursor-pointer file:rounded-none file:border-0 file:px-3 file:text-neutral-700 bg-clip-padding px-3 py-1.5 file:me-3 mt-2">
                            <span asp-validation-for="CandidateProfileUrl" class="text-red-600"></span>
                        </div>
                    </div><!--end grid-->

                    <div class="grid grid-cols-1">
                        <div class="mt-5">
                            <label asp-for="Description" class="form-label font-medium">Description : </label>
                            <textarea id="descriptionId" asp-for="Description" class="form-input border border-slate-100 dark:border-slate-800 mt-2 textarea" placeholder="Description :"></textarea>
                             <span asp-validation-for="Description" class="text-red-600"></span>
                        </div>
                        <div class="mt-5">
                             <label asp-for="CandidateSkillName" class="form-label font-medium">Skills : </label>
                            <input id="skillInput" asp-for="CandidateSkillName" class="form-input border border-slate-100 dark:border-slate-800 mt-2" placeholder="Problem Solving">
                            <button type="button" id="addSkill" class="btn mt-3 rounded-md bg-emerald-600 hover:bg-emerald-700 border-emerald-600 hover:border-emerald-700 text-white">Add Skill</button>
                        </div>
                        <ul class="list-none mt-1" id="skillCollection">
                            @foreach (var item in ViewBag.Skills)
                            {
                                <li class="inline-flex items-center py-2 px-4 bg-white me-2 my-1 shadow dark:shadow-gray-700 rounded-md">
                                    <span onclick="deleteSkill(this)" class="mdi mdi-delete-empty text-xl cursor-pointer"></span>
                                    <div class="ms-4">
                                        <span class="text-emerald-600 font-medium text-sm">@item</span>
                                    </div>
                                </li>
                            }
                        </ul>
                    </div><!--end row-->

                    <input type="submit" id="addCandidate" class="btn bg-emerald-600 hover:bg-emerald-700 text-white rounded-md mt-5" value="Save Changes">
                </form><!--end form-->
            </div>

            

            <div class="p-6 rounded-md shadow dark:shadow-gray-800 bg-white dark:bg-slate-900">
                <h5 class="text-lg font-semibold mb-5 text-red-600">Delete Account :</h5>

                <p class="text-slate-400 mb-4">Do you want to delete the account? Please press below "Delete" button</p>

                <a style="background-color:#dc2626 !important;" asp-action="Delete" asp-controller="Candidates" asp-route-id="@Model.Id" class="btn  text-white rounded-md">Delete</a>
            </div>
        </div>
    </div>
</section>
<!-- End -->

@section scripts{
<script>
    const skills = [];
    const addSkill = document.querySelector('#addSkill'),
        skillCollection = document.querySelector('#skillCollection'),
        addCandidate = document.querySelector('#addCandidate'),
        skillInput = document.querySelector('#skillInput');
        
        skillInput.value='';

        [...skillCollection.children].forEach(element => {
            skills.push(element.children[1].children[0].textContent);
        });

       
        

        addSkill.addEventListener('click', function (e) {
            e.preventDefault();
            skillCollection.innerHTML +=
                `
                    <li class="inline-flex items-center py-2 px-4 bg-white me-2 my-1 shadow dark:shadow-gray-700 rounded-md">
                        <span onclick="deleteSkill(this)" class="mdi mdi-delete-empty text-xl cursor-pointer"></span>
                        <div class="ms-4">
                            <span class="text-emerald-600 font-medium text-sm">${skillInput.value}</span>
                        </div>
                    </li>
                   `
           

            skills.push(skillInput.value);
            skillInput.value = '';

             //skills.forEach(skill => {
             //     console.log(skill);
             //  });
        });

        

        addCandidate.addEventListener('click',function(e){
            e.preventDefault();

            
            const dataPost = JSON.stringify(skills),
            firstnameId = document.getElementById('firstnameId').value,
            lastnameId = document.getElementById('lastnameId').value,
            emailId = document.getElementById('emailId').value,
            professionId = document.getElementById('professionId').value,
            cvId = document.getElementById('cvId').files[0],
            imageId = document.getElementById('imageId').files[0],
            descriptionId = document.getElementById('descriptionId').value,
            countryId = document.getElementById('countryId').value,
            cityId = document.getElementById('cityId').value;
            
            const imageData = new FormData();
            const cvData = new FormData();


            console.log(firstnameId);
            console.log(lastnameId);
            console.log(professionId);
            console.log(emailId);
            console.log(cvId);
            console.log(imageId);
            console.log(descriptionId);
            console.log(countryId);
            console.log(cityId);

            //cvData.append(cvId.name,cvId);
            //imageData.append(imageId.name,imageId);

       
            $.ajax({
                 type: "POST",
                 url: "http://localhost:5194/Candidates/Edit",
                 
                 //cache: false,
                 data:{
                    skills: dataPost,
                    candidatefirstname:firstnameId,
                    candidatelastname:lastnameId,
                    candidateemail:emailId,
                    candidateprofession:professionId,
                    candidatecvurl:cvData.append(cvId.name,cvId),
                    candidateprofileurl: imageData.append(imageId.name, imageId),
                    description:descriptionId,
                    countryid:countryId,
                    cityid:cityId
                 },
                  
                  success: function (data) {
                      alert("good: " + data)
                  },
                  error: function (data) {
                      console.log(data)
                  }
              });
        });

        function deleteSkill(event) {
            skills.pop(event.nextElementSibling.children[0].textContent);
            event.parentElement.remove();
        };


</script>
}