JobStack/src/WebUI/ViewModels/JobApply/JobApplyPostDto.cs
namespace JobStack.WebUI.ViewModels.JobApply;

public class JobApplyPostDto
{
    public int VacancyId { get; set; }
    public string FirstName { get; set; } = null!;
    public string LastName { get; set; } = null!;
    public string EmailAddress { get; set; } = null!;
    public string? Description { get; set; }
    public IFormFile? CvFileUrl { get; set; }
}

JobStack/src/WebUI/Controllers/JobAppliesController.cs
using JobStack.WebUI.DTOs.JobApply;
using JobStack.WebUI.Utilities;
using JobStack.WebUI.ViewModels.JobApply;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using WebUI.Models;

namespace JobStack.WebUI.Controllers;

public class JobAppliesController : Controller
{
    Uri baseUrl = new("http://localhost:7264/api");
    private readonly HttpClient _client;
    private readonly IWebHostEnvironment _env;

    public JobAppliesController(HttpClient client, IWebHostEnvironment env)
    {
        _client = client;
        _client.BaseAddress = baseUrl;
        _env = env;
    }

    public IActionResult Index(int id)
    {
        ViewBag.DetailsId = id;
        List<JobApplyVM> jobApplies = new();
        HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + $"/JobApplies/GetAllJobAppliesVacancy/{id}").Result;
        if (response.IsSuccessStatusCode)
        {
            string data = response.Content.ReadAsStringAsync().Result;
            jobApplies = JsonConvert.DeserializeObject<List<JobApplyVM>>(data);
            return View(jobApplies);
        }
        return RedirectToAction("Index", "Error");
    }
    public IActionResult Details(int id)
    {
        List<JobApplyVM> jobs = new();
        HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + $"/JobApplies/Details/{id}").Result;
        if (response.IsSuccessStatusCode)
        {
            string data = response.Content.ReadAsStringAsync().Result;
            jobs = JsonConvert.DeserializeObject<List<JobApplyVM>>(data);
            return View(jobs[0]);
        }
        return RedirectToAction("Index", "Error");
    }



    [HttpGet]
    public IActionResult SendApply()
    {

        return View();
    }


    [HttpPost]
    public IActionResult SendApply(int id, JobApplyPostDto jobApply)
    {
        var folderPath = Path.Combine(_env.WebRootPath, "data", "jobapply");
        string returnPath = jobApply.CvFileUrl.SaveFile(folderPath);
        JobApplyDto job = new()
        {
            FirstName = jobApply.FirstName,
            LastName = jobApply.LastName,
            EmailAddress = jobApply.EmailAddress,
            Description = jobApply.Description,
            CvFileUrl = returnPath,
            VacancyId = id
        };
        string data = JsonConvert.SerializeObject(job);
        StringContent content = new(data, Encoding.UTF8, "application/json");
        HttpResponseMessage response = _client.PostAsync(_client.BaseAddress + "/JobApplies/Post", content).Result;
        if (response.IsSuccessStatusCode)
        {
            return RedirectToAction("Index", "Thank");
        }
        return RedirectToAction("Index", "Error");
    }
}

JobStack/src/WebUI/Views/JobApplies/Index.cshtml
@model List<JobApplyVM>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutWhite.cshtml";
}

<!-- Start Hero -->
<section style="background-image:url('https://shreethemes.in/jobstack/layouts/assets/images/hero/bg.jpg');" class="relative table w-full py-36  bg-top bg-no-repeat bg-cover">
    <div class="absolute inset-0 bg-emerald-900/90"></div>
    <div class="container">
        <div class="grid grid-cols-1 text-center mt-10">
            <h3 class="md:text-3xl text-2xl md:leading-snug tracking-wide leading-snug font-medium text-white">Job Applies</h3>
        </div><!--end grid-->
    </div><!--end container-->

    <div class="absolute text-center z-10 bottom-5 start-0 end-0 mx-3">
        <ul class="breadcrumb tracking-[0.5px] breadcrumb-light mb-0 inline-block">
            <li class="inline breadcrumb-item text-[15px] font-semibold duration-500 ease-in-out text-white/50 hover:text-white"><a asp-controller="Home" asp-action="Index">Jobstack</a></li>
            <li class="inline breadcrumb-item text-[15px] font-semibold duration-500 ease-in-out text-white/50 hover:text-white"><a asp-controller="Companies" asp-action="Index">Companies</a></li>
            <li class="inline breadcrumb-item text-[15px] font-semibold duration-500 ease-in-out text-white/50 hover:text-white"><a asp-controller="Companies" asp-action="Details" asp-route-id="@ViewBag.DetailsId">Details</a></li>
            <li class="inline breadcrumb-item text-[15px] font-semibold duration-500 ease-in-out text-white" aria-current="page">Job Appliers</li>
        </ul>
    </div>
</section><!--end section-->
<div class="relative">
    <div class="shape absolute start-0 end-0 sm:-bottom-px -bottom-[2px] overflow-hidden z-1 text-white dark:text-slate-900">
        <svg class="w-full h-auto" viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
        </svg>
    </div>
</div>
<!-- End Hero -->
<!-- Start -->
<section class="relative md:py-24 py-16">
    <div class="container">
        <div class="grid xl:grid-cols-4 lg:grid-cols-3 md:grid-cols-2 grid-cols-1 gap-[30px]">
            @foreach (var jobApply in Model)
            {
                <div class="group bg-white dark:bg-slate-900 relative overflow-hidden rounded-md shadow dark:shadow-gray-700 text-center p-6">

                    <div class="mt-2">
                        <a asp-controller="JobApplies" asp-action="Details" asp-route-id="@jobApply.Id" class="hover:text-emerald-600 font-semibold text-lg">@jobApply.FirstName @jobApply.LastName</a>
                    </div>

                    @* <ul class="mt-2 list-none">
                <li class="inline"><span class="bg-emerald-600/10 inline-block text-emerald-600 text-xs px-2.5 py-0.5 font-semibold rounded-full">Design</span></li>
                <li class="inline"><span class="bg-emerald-600/10 inline-block text-emerald-600 text-xs px-2.5 py-0.5 font-semibold rounded-full">UI</span></li>
                <li class="inline"><span class="bg-emerald-600/10 inline-block text-emerald-600 text-xs px-2.5 py-0.5 font-semibold rounded-full">Digital</span></li>
                </ul>*@

                    @*<div class="flex justify-between mt-2">
                <div class="block">
                <span class="text-slate-400">Salery:</span>
                <span class="block text-sm font-semibold">$4k - $4.5k</span>
                </div>
                <div class="block">
                <span class="text-slate-400">Experience:</span>
                <span class="block text-sm font-semibold">2 Years</span>
                </div>
                </div>*@

                    <div class="mt-3">
                        <a asp-controller="JobApplies" asp-action="Details" asp-route-id="@jobApply.Id" class="btn btn-sm bg-emerald-600 hover:bg-emerald-700 border-emerald-600 dark:border-emerald-600 text-white rounded-md">Profile</a>
                        
                        @*<a asp-controller="JobApplies" asp-action="Details" asp-route-id="@jobApply.Id" class="btn btn-sm bg-emerald-600 hover:bg-emerald-700 border-emerald-600 dark:border-emerald-600 text-white rounded-md">Profile</a>*@
                        @*<a href="~/data/jobapply/@jobApply.CvFile" class="btn bg-emerald-600 hover:bg-emerald-700 border-emerald-600 dark:border-emerald-600 text-white rounded-md w-full" download><i class="uil uil-file-download-alt"></i> Download CV</a>*@

                        <a href="~/data/jobapply/@jobApply.CvFile" class="btn btn-sm btn-icon bg-emerald-600/5 hover:bg-emerald-600 border-emerald-600/10 hover:border-emerald-600 text-emerald-600 hover:text-white rounded-full ms-1" download><i class="uil uil-file-download-alt"></i></a>
                    </div>

                    @*<span class="absolute top-[10px] end-4">
                <a href="javascript:void(0)" class="text-slate-100 dark:text-slate-700 focus:text-red-600 dark:focus:text-red-600 hover:text-red-600 dark:hover:text-red-600 text-2xl"><i class="mdi mdi-heart"></i></a>
                </span>*@
                </div>

                <!--end content-->
            }



        </div><!--end grid-->

        <div class="grid md:grid-cols-12 grid-cols-1 mt-8">
            <div class="md:col-span-12 text-center">
                <nav aria-label="Page navigation example">
                    <ul class="inline-flex items-center -space-x-px">
                        <li>
                            <a href="#" class="w-[40px] h-[40px] inline-flex justify-center items-center text-slate-400 bg-white dark:bg-slate-900 rounded-s-3xl hover:text-white border border-gray-100 dark:border-gray-800 hover:border-emerald-600 dark:hover:border-emerald-600 hover:bg-emerald-600 dark:hover:bg-emerald-600">
                                <i class="uil uil-angle-left text-[20px] rtl:rotate-180 rtl:-mt-1"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#" aria-current="page" class="z-10 w-[40px] h-[40px] inline-flex justify-center items-center text-white bg-emerald-600 border border-emerald-600">1</a>
                        </li>
                        <li>
                            <a href="#" class="w-[40px] h-[40px] inline-flex justify-center items-center text-slate-400 hover:text-white bg-white dark:bg-slate-900 border border-gray-100 dark:border-gray-800 hover:border-emerald-600 dark:hover:border-emerald-600 hover:bg-emerald-600 dark:hover:bg-emerald-600">2</a>
                        </li>
                        <li>
                            <a href="#" class="w-[40px] h-[40px] inline-flex justify-center items-center text-slate-400 hover:text-white bg-white dark:bg-slate-900 border border-gray-100 dark:border-gray-800 hover:border-emerald-600 dark:hover:border-emerald-600 hover:bg-emerald-600 dark:hover:bg-emerald-600">3</a>
                        </li>
                        <li>
                            <a href="#" class="w-[40px] h-[40px] inline-flex justify-center items-center text-slate-400 hover:text-white bg-white dark:bg-slate-900 border border-gray-100 dark:border-gray-800 hover:border-emerald-600 dark:hover:border-emerald-600 hover:bg-emerald-600 dark:hover:bg-emerald-600">4</a>
                        </li>
                        <li>
                            <a href="#" class="w-[40px] h-[40px] inline-flex justify-center items-center text-slate-400 hover:text-white bg-white dark:bg-slate-900 border border-gray-100 dark:border-gray-800 hover:border-emerald-600 dark:hover:border-emerald-600 hover:bg-emerald-600 dark:hover:bg-emerald-600">5</a>
                        </li>
                        <li>
                            <a href="#" class="w-[40px] h-[40px] inline-flex justify-center items-center text-slate-400 bg-white dark:bg-slate-900 rounded-e-3xl hover:text-white border border-gray-100 dark:border-gray-800 hover:border-emerald-600 dark:hover:border-emerald-600 hover:bg-emerald-600 dark:hover:bg-emerald-600">
                                <i class="uil uil-angle-right text-[20px] rtl:rotate-180 rtl:-mt-1"></i>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div><!--end col-->
        </div><!--end grid-->
    </div><!--end container-->

    <div class="container-fluid md:mt-24 mt-16">
        <div class="container">
            <div class="grid grid-cols-1">
                <div class="relative overflow-hidden lg:px-8 px-6 py-10 rounded-xl shadow-lg dark:shadow-gray-700">
                    <div class="grid md:grid-cols-12 grid-cols-1 items-center gap-[30px]">
                        <div class="lg:col-span-8 md:col-span-7">
                            <div class="ltr:md:text-left rtl:md:text-right text-center relative z-1">
                                <h3 class="text-2xl font-semibold text-black dark:text-white mb-4">Explore a job now!</h3>
                                <p class="text-slate-400 max-w-xl">Search all the open positions on the web. Get your own personalized salary estimate. Read reviews on over 30000+ companies worldwide.</p>
                            </div>
                        </div>

                        <div class="lg:col-span-4 md:col-span-5">
                            <div class="ltr:text-right rtl:text-left relative z-1">
                                <a href="employer-detail.html" class="btn bg-emerald-600 hover:bg-emerald-700 border-emerald-600 dark:border-emerald-600 text-white rounded-md">Apply Now</a>
                                <a href="aboutus.html" class="btn bg-emerald-600/5 hover:bg-emerald-600 border-emerald-600/10 hover:border-emerald-600 text-emerald-600 hover:text-white rounded-md ms-2">Learn More</a>
                            </div>
                        </div>
                    </div>

                    <div class="absolute -top-5 -start-5">
                        <div class="uil uil-envelope lg:text-[150px] text-7xl text-black/5 dark:text-white/5 ltr:-rotate-45 rtl:rotate-45"></div>
                    </div>

                    <div class="absolute -bottom-5 -end-5">
                        <div class="uil uil-pen lg:text-[150px] text-7xl text-black/5 dark:text-white/5 rtl:-rotate-90"></div>
                    </div>
                </div>
            </div>
        </div>
    </div><!--end container-->
</section><!--end section-->
<!-- End -->

JobStack/src/WebUI/Views/JobApplies/SendApply.cshtml
@model JobApplyPostDto
@{
    ViewData["Title"] = "SendApply";
    Layout = "~/Views/Shared/_LayoutWhite.cshtml";
}

<!-- Start Hero -->
<section style="background-image:url('https://shreethemes.in/jobstack/layouts/assets/images/hero/bg.jpg');" class="relative table w-full py-36  bg-top bg-no-repeat bg-cover">
    <div class="absolute inset-0 bg-emerald-900/90"></div>
    <div class="container">
        <div class="grid grid-cols-1 text-center mt-10">
            @*<h3 class="md:text-3xl text-2xl md:leading-snug tracking-wide leading-snug font-medium text-white">@Model.Vacancy.TitleName</h3>*@

        </div><!--end grid-->
    </div><!--end container-->

    <div class="absolute text-center z-10 bottom-5 start-0 end-0 mx-3">
        <ul class="breadcrumb tracking-[0.5px] breadcrumb-light mb-0 inline-block">
            <li class="inline breadcrumb-item text-[15px] font-semibold duration-500 ease-in-out text-white/50 hover:text-white"><a asp-controller="Home" asp-action="Index">Jobstack</a></li>
            <li class="inline breadcrumb-item text-[15px] font-semibold duration-500 ease-in-out text-white" aria-current="page">Job apply form</li>
        </ul>
    </div>
</section><!--end section-->
<div class="relative">
    <div class="shape absolute start-0 end-0 sm:-bottom-px -bottom-[2px] overflow-hidden z-1 text-slate-50 dark:text-slate-800">
        <svg class="w-full h-auto" viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
        </svg>
    </div>
</div>
<!-- End Hero -->
<!-- Start -->
<section class="relative bg-slate-50 dark:bg-slate-800 lg:py-24 py-16">
    <div class="container">
        <div class="md:flex justify-center">
            <div class="lg:w-2/4 md:w-2/3">
                <div class="p-6 bg-white dark:bg-slate-900 shadow dark:shadow-gray-700 rounded-md">
                    <form asp-action="SendApply"  enctype="multipart/form-data" class="text-left">
                        <div class="grid grid-cols-1">
                            <div asp-validation-summary="ModelOnly" class="text-red-800"></div>
                            <div class="mb-4 ltr:text-left rtl:text-right">
                                <label class="font-semibold" asp-for="FirstName">Your FirstName:</label>
                                <input asp-for="FirstName" autocomplete="off" class="form-input border border-slate-100 dark:border-slate-800 mt-1" placeholder="Harry">
                                <span asp-validation-for="FirstName" class="text-red-800"></span>
                            </div> 
                            
                            <div class="mb-4 ltr:text-left rtl:text-right">
                                <label class="font-semibold" asp-for="LastName">Your LastName:</label>
                                <input asp-for="LastName" autocomplete="off" class="form-input border border-slate-100 dark:border-slate-800 mt-1" placeholder="Harry">
                                <span asp-validation-for="LastName" class="text-red-800"></span>
                            </div>

                            <div class="mb-4 ltr:text-left rtl:text-right">
                                <label class="font-semibold" asp-for="EmailAddress">Email Address:</label>
                                <input asp-for="EmailAddress" autocomplete="off" class="form-input border border-slate-100 dark:border-slate-800 mt-1" placeholder="name@example.com">
                                <span asp-validation-for="EmailAddress" class="text-red-800"></span>

                            </div>

                            

                            <div class="mb-2 ltr:text-left rtl:text-right">
                                <label asp-for="Description" class="font-semibold">Coverting Letter:</label>
                                <textarea asp-for="Description" autocomplete="off" class="form-input border border-slate-100 dark:border-slate-800 mt-1 textarea" placeholder="Message :"></textarea>
                                <span asp-validation-for="Description" class="text-red-800"></span>

                            </div>

                            <div class="mb-4 ltr:text-left rtl:text-right">
                                <label class="font-semibold" asp-for="CvFileUrl">Upload Resume:</label>
                                <input asp-for="CvFileUrl"  class="relative form-input border border-slate-100 dark:border-slate-800 file:h-10 file:-mx-3 file:-my-2 file:cursor-pointer file:rounded-none file:border-0 file:px-3 file:text-neutral-700 bg-clip-padding px-3 py-1.5 file:me-3 mt-1">
                                <span asp-validation-for="CvFileUrl" class="text-red-800"></span>

                            </div>

                            <div>
                                <button   class="btn rounded-md bg-emerald-600 hover:bg-emerald-700 border-emerald-600 hover:border-emerald-700 text-white">Send</button>
                            </div>
                        </div>
                    </form><!--end form-->
                </div>
            </div>
        </div><!--end flex-->
    </div><!--end container-->
</section><!--end section-->
<!-- End -->