JobStack/src/WebUI/Areas/Manage/Controllers/VacancyController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using WebUI.Models;

namespace JobStack.WebUI.Areas.Manage.Controllers;

[Area("Manage")]
public class VacancyController : Controller
{
    Uri baseUrl = new("http://localhost:7264/api");
    private readonly HttpClient _client;
    private readonly IWebHostEnvironment _env;
    private readonly string root = Path.Combine(Directory.GetParent("JobStack").Parent.Parent.Parent.ToString(), "JobstackApp", "JobApp", "assets", "vacancies.json");


    public VacancyController(HttpClient client, IWebHostEnvironment env)
    {
        _client = client;
        _client.BaseAddress = baseUrl;
        _env = env;
    }
    private string JsonData()
    {
        // List<VacancyVM> vacancies = new();
        string data = "";
        HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Vacancies/GetAllVacancies").Result;
        if (response.IsSuccessStatusCode)
        {
            data = response.Content.ReadAsStringAsync().Result;
            //vacancies = JsonConvert.DeserializeObject<List<VacancyVM>>(data);
        }
        return data;
    }

    public IActionResult Index()
    {
        List<VacancyVM> vacancies = new();
        HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Vacancies/ManageGetAllVacancies").Result;
        if (response.IsSuccessStatusCode)
        {
            string data = response.Content.ReadAsStringAsync().Result;
            vacancies = JsonConvert.DeserializeObject<List<VacancyVM>>(data);
            //System.IO.File.WriteAllText(root, JsonData());
            return View(vacancies);
        }
        return RedirectToAction("Index", "Errors");

    }
    public IActionResult Delete(int id)
    {
        string data = id.ToString();
        StringContent content = new(data, Encoding.UTF8, "application/json");
        HttpResponseMessage result = _client.PostAsync(_client.BaseAddress + $"/Vacancies/Delete?id={id}", content).Result;
        if (result.IsSuccessStatusCode)
        {
            // System.IO.File.WriteAllText(root, JsonData());
            return RedirectToAction(nameof(Index));

        }
        return RedirectToAction("Index", "Errors");

    }
    [HttpGet]
    public IActionResult PermaDelete(int id)
    {
        List<VacancyVM> vacancies = new();
        HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + $"/Vacancies/Details/{id}").Result;
        if (response.IsSuccessStatusCode)
        {
            string data = response.Content.ReadAsStringAsync().Result;
            vacancies = JsonConvert.DeserializeObject<List<VacancyVM>>(data);
            ViewBag.Responsibilits = JsonConvert.DeserializeObject<string[]>(vacancies[0].ResponsibilityName);
            ViewBag.Skills = JsonConvert.DeserializeObject<string[]>(vacancies[0].SkillName);
            return View(vacancies[0]);
        }
        return RedirectToAction("Index", "Errors");

    }
    [HttpPost, ActionName(nameof(PermaDelete))]
    public IActionResult DeleteConfirmed(int id)
    {
        string data = id.ToString();
        StringContent content = new(data, Encoding.UTF8, "application/json");
        HttpResponseMessage result = _client.PostAsync(_client.BaseAddress + $"/Vacancies/PermaDelete?id={id}", content).Result;
        HttpResponseMessage response = result;
        if (response.IsSuccessStatusCode)
        {
            // System.IO.File.WriteAllText(root, JsonData());
            return RedirectToAction(nameof(Index));
        }
        return RedirectToAction("Index", "Errors");
    }
}

JobStack/src/WebUI/Controllers/VacanciesController.cs
using JobStack.WebUI.DTOs.Vacancy;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using WebUI.Models;

namespace JobStack.WebUI.Controllers;

public class VacanciesController : Controller
{
    Uri baseUrl = new("http://localhost:7264/api");
    private readonly HttpClient _client;
    private readonly IWebHostEnvironment _env;
    private readonly string root = Path.Combine(Directory.GetParent("JobStack").Parent.Parent.Parent.ToString(), "JobstackApp", "JobApp", "assets", "vacancies.json");
    // private readonly string root = Path.Combine(Directory.GetParent("JobStack").Parent.Parent.ToString(), "src", "test.json");


    public VacanciesController(HttpClient client, IWebHostEnvironment env)
    {
        _client = client;
        _client.BaseAddress = baseUrl;
        _env = env;
    }

    private List<CountryVM> CountryAll()
    {
        List<CountryVM> countries = new();
        HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Countries/GetAllCountries").Result;
        if (response.IsSuccessStatusCode)
        {
            string data = response.Content.ReadAsStringAsync().Result;
            countries = JsonConvert.DeserializeObject<List<CountryVM>>(data);
        }
        return countries;
    }
    private List<CityVM> CityAll()
    {
        List<CityVM> cities = new();
        HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Cities/GetAllCities").Result;
        if (response.IsSuccessStatusCode)
        {
            string data = response.Content.ReadAsStringAsync().Result;
            cities = JsonConvert.DeserializeObject<List<CityVM>>(data);
        }
        return cities;
    }
    private List<CategoryVM> CategoryAll()
    {
        List<CategoryVM> categories = new();
        HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Categories/GetAllCategories").Result;
        if (response.IsSuccessStatusCode)
        {
            string data = response.Content.ReadAsStringAsync().Result;
            categories = JsonConvert.DeserializeObject<List<CategoryVM>>(data);
        }
        return categories;
    }
    private List<JobTypeVM> TypeAll()
    {
        List<JobTypeVM> jobTypes = new();
        HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/JobTypes/GetAllTypes").Result;
        if (response.IsSuccessStatusCode)
        {
            string data = response.Content.ReadAsStringAsync().Result;
            jobTypes = JsonConvert.DeserializeObject<List<JobTypeVM>>(data);
        }
        return jobTypes;
    }
    public IActionResult Index()
    {
        List<VacancyVM> vacancies = new();
        HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Vacancies/GetAllVacancies").Result;
        if (response.IsSuccessStatusCode)
        {
            string data = response.Content.ReadAsStringAsync().Result;
            vacancies = JsonConvert.DeserializeObject<List<VacancyVM>>(data);
            return View(vacancies);

        }
        return RedirectToAction("Index", "Error");
    }
    private string JsonData()
    {
        // List<VacancyVM> vacancies = new();
        string data = "";
        HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Vacancies/GetAllVacancies").Result;
        if (response.IsSuccessStatusCode)
        {
            data = response.Content.ReadAsStringAsync().Result;
            //vacancies = JsonConvert.DeserializeObject<List<VacancyVM>>(data);
        }
        return data;
    }
    [HttpGet]
    public IActionResult Details(int id)
    {
        List<VacancyVM> vacancies = new();
        HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + $"/Vacancies/Details/{id}").Result;
        if (response.IsSuccessStatusCode)
        {
            string data = response.Content.ReadAsStringAsync().Result;
            vacancies = JsonConvert.DeserializeObject<List<VacancyVM>>(data);
            ViewBag.Responsibilits = JsonConvert.DeserializeObject<string[]>(vacancies[0].ResponsibilityName);
            ViewBag.Skills = JsonConvert.DeserializeObject<string[]>(vacancies[0].SkillName);
            return View(vacancies[0]);
        }
        return RedirectToAction("Index", "Error");
    }
    [HttpGet]
    public IActionResult Create(int id)
    {
        TempData["CompanyId"] = id;
        ViewBag.Countries = CountryAll();
        ViewBag.Cities = CityAll();
        ViewBag.Categories = CategoryAll();
        ViewBag.Types = TypeAll();
        return View();
    }
    [HttpPost]
    public IActionResult Create(VacancyPostDto vacancy, string responsibilts, string skills)
    {
        string test = root;
        //"D:\Personal\JobStackProject\JobstackApp\JobApp\assets\vacancies.json"
        VacancyPostDto vacancyPost = new()
        {
            CompanyId = (int)TempData["CompanyId"],
            Address = vacancy.Address,
            CategoryId = vacancy.CategoryId,
            CityId = vacancy.CityId,
            CountryId = vacancy.CountryId,
            Description = vacancy.Description,
            Experience = vacancy.Experience,
            JobTypeId = vacancy.JobTypeId,
            ResponsibilityName = responsibilts,
            Salary = vacancy.Salary,
            SkillName = skills,
            TitleName = vacancy.TitleName
        };
        string data = JsonConvert.SerializeObject(vacancyPost);
        StringContent content = new(data, Encoding.UTF8, "application/json");
        HttpResponseMessage response = _client.PostAsync(_client.BaseAddress + "/Vacancies/Post", content).Result;
        if (response.IsSuccessStatusCode)
        {
            //using (FileStream fs = new FileStream(root, FileMode.Open, FileAccess.ReadWrite))
            //{
            //    using (StreamWriter sw = new(fs))
            //    {
            //        sw.Write(JsonData());
            //    }
            //}

            // System.IO.File.WriteAllText(root, JsonData());


            return RedirectToAction(nameof(Index));
        }
        return RedirectToAction("Index", "Error");
    }
    [HttpGet]
    public IActionResult Edit(int id)
    {
        List<VacancyUpdateDto> vacancies = new();
        HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + $"/Vacancies/Details/{id}").Result;
        if (response.IsSuccessStatusCode)
        {
            string data = response.Content.ReadAsStringAsync().Result;
            vacancies = JsonConvert.DeserializeObject<List<VacancyUpdateDto>>(data);
            ViewBag.Responsibility = JsonConvert.DeserializeObject<string[]>(vacancies[0].ResponsibilityName);
            ViewBag.Skillss = JsonConvert.DeserializeObject<string[]>(vacancies[0].SkillName);
            ViewBag.Countries = CountryAll();
            ViewBag.Cities = CityAll();
            ViewBag.Categories = CategoryAll();
            ViewBag.Types = TypeAll();
            TempData["VacancyId"] = id;
            return View(vacancies[0]);
        }
        return RedirectToAction("Index", "Error");
    }
    [HttpPost]
    public IActionResult Edit(VacancyUpdateDto vacancy, string responsible, string skillsebla)
    {

        VacancyUpdateDto vacancyUpdate = new()
        {
            VacancyId = (int)TempData["VacancyId"],
            TitleName = vacancy.TitleName,
            Address = vacancy.Address,
            CategoryId = vacancy.CategoryId,
            CityId = vacancy.CityId,
            CountryId = vacancy.CountryId,
            Description = vacancy.Description,
            Experience = vacancy.Experience,
            JobTypeId = vacancy.JobTypeId,
            ResponsibilityName = responsible,
            Salary = vacancy.Salary,
            SkillName = skillsebla,
        };
        string data = JsonConvert.SerializeObject(vacancyUpdate);
        StringContent content = new(data, Encoding.UTF8, "application/json");
        HttpResponseMessage result = _client.PutAsync(_client.BaseAddress + "/Vacancies/Put", content).Result;
        HttpResponseMessage response = result;
        if (response.IsSuccessStatusCode)
        {
            //System.IO.FileMode.Open;
            //System.IO.File.WriteAllText(root, JsonData());
            return RedirectToAction(nameof(Index));
        }
        return RedirectToAction("Index", "Error");
    }

    public IActionResult Delete(int id)
    {
        string data = id.ToString();
        StringContent content = new(data, Encoding.UTF8, "application/json");
        HttpResponseMessage result = _client.PostAsync(_client.BaseAddress + $"/Vacancies/Delete?id={id}", content).Result;
        if (result.IsSuccessStatusCode)
        {
            //System.IO.File.WriteAllText(root, JsonData());
            return RedirectToAction(nameof(Index));
        }
        return RedirectToAction("Index", "Error");
    }
}

JobStack/src/WebUI/Views/Vacancies/Details.cshtml
@model VacancyVM
@{
    ViewData["Title"] = "Details";
}

<!-- Start -->
<section class="bg-slate-50 dark:bg-slate-800 md:py-24 py-16">
    <div class="container mt-10">
        <div class="grid md:grid-cols-12 grid-cols-1 gap-[30px]">
            <div class="lg:col-span-8 md:col-span-6">
                <div class="md:flex items-center p-6 shadow dark:shadow-gray-700 rounded-md bg-white dark:bg-slate-900">
                    <img src="~/data/company/@Model.Company.CompanyLogo" class="rounded-full h-28 w-28 p-4 bg-white dark:bg-slate-900 shadow dark:shadow-gray-700" alt="">

                    <div class="md:ms-4 md:mt-0 mt-6">
                        <h5 class="text-xl font-semibold">@Model.TitleName</h5>
                        <div class="mt-2">
                            <span class="text-slate-400 font-medium me-2 inline-block"><i class="uil uil-building text-[18px] text-emerald-600 me-1"></i> @Model.Company.CompanyName</span>
                            <span class="text-slate-400 font-medium me-2 inline-block"><i class="uil uil-map-marker text-[18px] text-emerald-600 me-1"></i> @Model.City.CityName, @Model.Country.Name</span>

                            <span class="text-slate-400 font-medium me-2 inline-block"><a asp-controller="JobApplies" asp-action="Index" asp-route-id="@Model.Id" class="btn btn-sm bg-emerald-600 hover:bg-emerald-700 border-emerald-600 dark:border-emerald-600 text-white rounded-md">See Apply</a></span>
                        </div>
                    </div>
                </div>

                <h5 class="text-lg font-semibold mt-6">Job Description:</h5>

                <p class="text-slate-400 mt-4">@Model.Description .</p>
                @*<p class="text-slate-400 mt-4">This means that Lorem Ipsum cannot accurately represent, for example, German, in which all nouns are capitalized. Thus, Lorem Ipsum has only limited suitability as a visual filler for German texts. If the fill text is intended to illustrate the characteristics of different typefaces.</p>
                <p class="text-slate-400 mt-4">It sometimes makes sense to select texts containing the various letters and symbols specific to the output language.</p>*@

                <h5 class="text-lg font-semibold mt-6">Responsibilities and Duties: </h5>
                <p class="text-slate-400 mt-4">It sometimes makes sense to select texts containing the various letters and symbols specific to the output language.</p>
                <ul class="list-none">
                    
                    @foreach (var item in ViewBag.Responsibilits)
                    {
                      <li class="text-slate-400 mt-2"><i class="uil uil-arrow-right text-emerald-600 me-1"></i>@item</li>
                        
                    }

                   
                </ul>

                <h5 class="text-lg font-semibold mt-6">Required Experience, Skills and Qualifications: </h5>
                <p class="text-slate-400 mt-4">It sometimes makes sense to select texts containing the various letters and symbols specific to the output language.</p>
                <ul class="list-none">
                    @foreach (var item in ViewBag.Skills)
                    {
                      <li class="text-slate-400 mt-2"><i class="uil uil-arrow-right text-emerald-600 me-1"></i>@item</li>
                        
                    }
                    
                </ul>

                <div class="mt-5">
                    <a asp-controller="JobApplies" asp-action="SendApply" asp-route-id="@Model.Id"  class="btn rounded-md bg-emerald-600 hover:bg-emerald-700 border-emerald-600 hover:border-emerald-700 text-white md:ms-2 w-full md:w-auto">Apply Now</a>
                </div>
            </div><!--end col-->

            <div class="lg:col-span-4 md:col-span-6">
                <div class="shadow dark:shadow-gray-700 rounded-md bg-white dark:bg-slate-900 sticky top-20">
                    <div class="p-6">
                        <h5 class="text-lg font-semibold">Job Information</h5>
                    </div>
                    <div class="p-6 border-t border-slate-100 dark:border-t-gray-700">
                        <ul class="list-none">
                            <li class="flex items-center">
                                <i data-feather="user-check" class="h-5 w-5"></i>

                                <div class="ms-4">
                                    <p class="font-medium">Employee Type:</p>
                                    <span class="text-emerald-600 font-medium text-sm">@Model.JobType.TypeName</span>
                                </div>
                            </li>

                            <li class="flex items-center mt-3">
                                <i data-feather="map-pin" class="h-5 w-5"></i>

                                <div class="ms-4">
                                    <p class="font-medium">Location:</p>
                                    <span class="text-emerald-600 font-medium text-sm">@Model.City.CityName, @Model.Country.Name</span>
                                </div>
                            </li>

                            <li class="flex items-center mt-3">
                                <i data-feather="monitor" class="h-5 w-5"></i>

                                <div class="ms-4">
                                    <p class="font-medium">Category:</p>
                                    <span class="text-emerald-600 font-medium text-sm">@Model.Category.CategoryName</span>
                                </div>
                            </li>

                            <li class="flex items-center mt-3">
                                <i data-feather="briefcase" class="h-5 w-5"></i>

                                <div class="ms-4">
                                    <p class="font-medium">Experience:</p>
                                    <span class="text-emerald-600 font-medium text-sm">@Model.Experience</span>
                                </div>
                            </li>

                            @*<li class="flex items-center mt-3">
                                <i data-feather="book" class="h-5 w-5"></i>

                                <div class="ms-4">
                                    <p class="font-medium">Qualifications:</p>
                                    <span class="text-emerald-600 font-medium text-sm">MCA</span>
                                </div>
                            </li>*@

                            <li class="flex items-center mt-3">
                                <i data-feather="dollar-sign" class="h-5 w-5"></i>

                                <div class="ms-4">
                                    <p class="font-medium">Salary:</p>
                                    <span class="text-emerald-600 font-medium text-sm">@Model.Salary</span>
                                </div>
                            </li>

                            <li class="flex items-center mt-3">
                                <i data-feather="clock" class="h-5 w-5"></i>

                                <div class="ms-4">
                                    <p class="font-medium">Date posted:</p>
                                    <span class="text-emerald-600 font-medium text-sm">@Model.Created.Day @Model.Created.Month @Model.Created.Year</span>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div><!--end col-->
        </div><!--end grid-->
    </div><!--end container-->

    <div class="container lg:mt-24 mt-16">
        <div class="grid grid-cols-1 pb-8 text-center">
            <h3 class="mb-4 md:text-[26px] md:leading-normal text-2xl leading-normal font-semibold">Related Vacancies</h3>

            <p class="text-slate-400 dark:text-slate-300 max-w-xl mx-auto">Search all the open positions on the web. Get your own personalized salary estimate. Read reviews on over 30000+ companies worldwide.</p>
        </div><!--end grid-->

        <div class="grid lg:grid-cols-3 md:grid-cols-2 mt-8 gap-[30px]">
           @* @foreach (var item in Model.Company.Vacancies.Take(3))
            {
              <div class="group shadow dark:shadow-gray-700 p-6 rounded-md bg-white dark:bg-slate-900">
                <div class="flex items-center justify-between">
                    <div class="flex items-center">
                        <div class="w-14 h-14 flex items-center justify-center bg-white dark:bg-slate-900 shadow dark:shadow-gray-700 rounded-md">
                            <img src="~/data/company/@item.Company.CompanyLogo" class="h-8 w-8" alt="">
                        </div>

                        <div class="ms-3">
                                <a asp-controller="Vacancies" asp-action="Details" asp-route-id="@item.Id" class="block text-[16px] font-semibold hover:text-emerald-600 transition-all duration-500">@item.Company.CompanyName</a>
                            <span class="block text-sm text-slate-400">@item.Created.Day days ago</span>
                        </div>
                    </div>

                    <span class="bg-emerald-600/10 group-hover:bg-emerald-600 inline-block text-emerald-600 group-hover:text-white text-xs px-2.5 py-0.5 font-semibold rounded-full transition-all duration-500">@item.JobType.TypeName</span>
                </div>

                <div class="mt-6">
                        <a asp-controller="Vacancies" asp-action="Details" asp-route-id="@item.Id" class="text-lg hover:text-emerald-600 font-semibold transition-all duration-500">@item.TitleName</a>
                    <h6 class="text-base font-medium"><i class="uil uil-map-marker"></i> @item.Country.Name</h6>
                </div>

               
            </div><!--end content-->
                
            }*@

           
        </div><!--end grid-->
    </div><!--end container-->

    <div class="container-fluid md:mt-24 mt-16">
        <div class="container">
            <div class="grid grid-cols-1">
                <div class="relative overflow-hidden lg:px-8 px-6 py-10 rounded-xl shadow-lg dark:shadow-gray-700">
                    <div class="grid md:grid-cols-12 grid-cols-1 items-center gap-[30px]">
                        <div class="lg:col-span-8 md:col-span-7">
                            <div class="ltr:md:text-left rtl:md:text-right text-center relative z-1">
                                <h3 class="text-2xl font-semibold text-black dark:text-white mb-4">Explore a job now!</h3>
                                <p class="text-slate-400 max-w-xl">Search all the open positions on the web. Get your own personalized salary estimate. Read reviews on over 30000+ companies worldwide.</p>
                            </div>
                        </div>

                        <div class="lg:col-span-4 md:col-span-5">
                            <div class="ltr:text-right rtl:text-left relative z-1">
                                <a href="employer-detail.html" class="btn bg-emerald-600 hover:bg-emerald-700 border-emerald-600 dark:border-emerald-600 text-white rounded-md">Apply Now</a>
                                <a href="aboutus.html" class="btn bg-emerald-600/5 hover:bg-emerald-600 border-emerald-600/10 hover:border-emerald-600 text-emerald-600 hover:text-white rounded-md ms-2">Learn More</a>
                            </div>
                        </div>
                    </div>

                    <div class="absolute -top-5 -start-5">
                        <div class="uil uil-envelope lg:text-[150px] text-7xl text-black/5 dark:text-white/5 ltr:-rotate-45 rtl:rotate-45"></div>
                    </div>

                    <div class="absolute -bottom-5 -end-5">
                        <div class="uil uil-pen lg:text-[150px] text-7xl text-black/5 dark:text-white/5 rtl:-rotate-90"></div>
                    </div>
                </div>
            </div><!--end grid-->
        </div><!--end container-->
    </div><!--end container-->
</section><!--end section-->
<!-- End -->

JobStack/src/WebUI/Views/Vacancies/Post.cshtml
@{
    ViewData["Title"] = "Post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Post</h1>